{% set name = "miller" %}
{% set version = "5.10.2" %}
{% set sha256 = "f48f6fb638ccceeebd3592bdec9966cd5f310728cf5c05bf4f5b5c38fca69c5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://johnkerl.org/miller-releases/miller-{{ version }}.conda.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - flex

test:
  commands:
    - mlr --version

about:
  home: http://johnkerl.org/miller/doc/index.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Miller is like awk, sed, cut, join, and sort for name-indexed data such as CSV, TSV,
    and tabular JSON. You get to work with your data using named fields, without needing to count
    positional column indices.'

extra:
  recipe-maintainers:
    - cbrueffer
    - zachcp
    - BEFH
