{% set name = "miller" %}
{% set version = "6.0.0" %}
{% set sha256 = "fca6d648212c30c9396868468ff6bd140bff57d324eac778e8ce8ae93ad52bed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/johnkerl/miller/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - flex

test:
  commands:
    - mlr --version

about:
  home: http://johnkerl.org/miller/doc/index.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Miller is like awk, sed, cut, join, and sort for name-indexed data such as CSV, TSV, and tabular JSON. You get to work with your data using named fields, without needing to count positional column indices.

extra:
  recipe-maintainers:
    - BEFH
    - cbrueffer
    - zachcp
