{% set name = "miller" %}
{% set version = "5.10.2" %}
{% set sha256 = "b6026479ee7315656d7ec228d0084f86d4cecc5b8b00d5400f5fb3600af65eb3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/johnkerl/miller/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go') }}
    - {{ compiler('cxx') }}
  host:
    - flex

test:
  commands:
    - mlr --version

about:
  home: http://johnkerl.org/miller/doc/index.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Miller is like awk, sed, cut, join, and sort for name-indexed data such as CSV, TSV,
    and tabular JSON. You get to work with your data using named fields, without needing to count
    positional column indices.'

extra:
  recipe-maintainers:
    - cbrueffer
    - zachcp
    - BEFH
