appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DVSMVGSU/WAoG0n5gF7ZAqiDh0980bOkY9v3Huw1HjDpIxWFuBg0c/GSpHUvkga8vdhYBiqCHK7L4Gh8XdrNb8TTl0xH2c2eYgaoUqcX1rN+LZnVS/+G2Kzs3Hv1j6v38Av4q5o8ajnW3MsQ+yYthdLFFV52qcWEXl59dx1N6t+Fy3nLOgz8VuhfL3V8G45TseCTwKvzzTfTz1Jvfkifkic/2I2xap+e9nJQ2php00NejJHDAEroKa+c3i2Vvsa16lnvp//Psm3UgUSZlV670FxBCxOZBzSSUG6ZSRV9caK3vvbYyjG/JZwKEuteYzs08Idkcyi+4usUFzpvBvtxKuuxgMg+wp73xokQMnCa517fdFn1KlTgrOBeAryXI9G+e/vH4s1bxIOQXbBQt1CHx5PBEp1UtOfD5sN/Xa57HSOQXix9EINLo/ou7wNfF5NxLEd0SQjV95r8jP+xjsumZK1t1Yd3XL3PFS+qMHPCKZzuKnThRJLHTShBF0hPyVtDEnQe4QueOOgDxJsmg5N3Fb3sDP1mZnwxa4z0Sj+k/zQ9VZYM+TMlS2DRomIop8YsJ+gwXJw1T0fTvIm1PD6BwGh8rp0zORhoJhe+SDWcXkq7adMQIWRbjLvvXzHsLgKOLp3C1rClYaAzrQ3TwiDB+WQ2ZkHUu4RvpzebvTnxip0=}
